// AUTO-GENERATED by scripts/build-icons.js — DO NOT EDIT BY HAND.
// Source: src/assets/icons/svg/*.svg
// To regenerate: `node scripts/build-icons.js`

import type { IconDef } from './types';

export type IconName =
  | 'alert'
  | 'app-fallback'
  | 'arrow-down'
  | 'arrow-left'
  | 'arrow-right'
  | 'arrow-up'
  | 'attachment'
  | 'bag-check'
  | 'bell'
  | 'bot'
  | 'box-list'
  | 'box-up'
  | 'building'
  | 'calculator'
  | 'calendar-route'
  | 'calendar'
  | 'camera'
  | 'card'
  | 'chat-star'
  | 'check'
  | 'chevron-down'
  | 'chevron-left'
  | 'chevron-right'
  | 'chevron-up'
  | 'circle-minus'
  | 'circle-plus'
  | 'clipboard-search'
  | 'clipboard-user'
  | 'clipboard'
  | 'close'
  | 'coin'
  | 'copy'
  | 'dashboard-megaphone'
  | 'dashboard-star'
  | 'download'
  | 'edit-pencil'
  | 'edit'
  | 'error'
  | 'eye-off'
  | 'eye'
  | 'file'
  | 'filter'
  | 'flag'
  | 'grid'
  | 'heart'
  | 'home'
  | 'image'
  | 'info'
  | 'keyboard'
  | 'lightbulb'
  | 'list'
  | 'location'
  | 'lock'
  | 'logout'
  | 'mail'
  | 'menu'
  | 'mic-on'
  | 'mic'
  | 'more-h'
  | 'more-v'
  | 'order'
  | 'package'
  | 'paperclip'
  | 'pause'
  | 'phone'
  | 'pin-search'
  | 'play'
  | 'plus'
  | 'qr'
  | 'refresh'
  | 'retry'
  | 'route'
  | 'scan'
  | 'scanner'
  | 'search'
  | 'send'
  | 'settings'
  | 'share'
  | 'shelf-pay'
  | 'shield-check'
  | 'sort'
  | 'sound'
  | 'spark'
  | 'star'
  | 'stop'
  | 'storefront-ai'
  | 'storefront-arrow'
  | 'storefront-check'
  | 'storefront-tag'
  | 'storefront'
  | 'success'
  | 'tag'
  | 'thinking'
  | 'trash'
  | 'upload'
  | 'user'
  | 'users-search'
  | 'visit'
  | 'warning';

export const ICONS: Record<IconName, IconDef> = {
  'alert': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M10.3 3.86 1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z',
      },
      {
        kind: 'path',
        d: 'M12 9v4',
      },
      {
        kind: 'path',
        d: 'M12 17h.01',
      },
    ],
  },
  'app-fallback': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M4 9V5a1 1 0 0 1 1-1h4',
      },
      {
        kind: 'path',
        d: 'M15 4h4a1 1 0 0 1 1 1v4',
      },
      {
        kind: 'path',
        d: 'M20 15v4a1 1 0 0 1-1 1h-4',
      },
      {
        kind: 'path',
        d: 'M9 20H5a1 1 0 0 1-1-1v-4',
      },
      {
        kind: 'path',
        d: 'M12 9v4',
      },
      {
        kind: 'circle',
        cx: 12,
        cy: 16.3,
        r: 0.95,
        fill: 'currentColor',
      },
    ],
  },
  'arrow-down': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M12 5v14',
      },
      {
        kind: 'path',
        d: 'M5 12l7 7 7-7',
      },
    ],
  },
  'arrow-left': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M19 12H5',
      },
      {
        kind: 'path',
        d: 'M12 5l-7 7 7 7',
      },
    ],
  },
  'arrow-right': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M5 12h14',
      },
      {
        kind: 'path',
        d: 'M13 5l7 7-7 7',
      },
    ],
  },
  'arrow-up': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M12 19V5',
      },
      {
        kind: 'path',
        d: 'M5 12l7-7 7 7',
      },
    ],
  },
  'attachment': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M14 4l-9 9a4 4 0 0 0 6 6l9-9a3 3 0 0 0-4-4l-8 8a2 2 0 0 0 3 3l7-7',
      },
    ],
  },
  'bag-check': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M5 7h14l-1.2 13H6.2z',
      },
      {
        kind: 'path',
        d: 'M9 7V5a3 3 0 0 1 6 0v2',
      },
      {
        kind: 'path',
        d: 'M9 13l2 2 4-4',
      },
    ],
  },
  'bell': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M6 17V11a6 6 0 1 1 12 0v6l1.5 2H4.5z',
      },
      {
        kind: 'path',
        d: 'M10 21a2 2 0 0 0 4 0',
      },
    ],
  },
  'bot': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 4,
        y: 8,
        width: 16,
        height: 12,
        rx: 3,
      },
      {
        kind: 'path',
        d: 'M12 4v4',
      },
      {
        kind: 'circle',
        cx: 12,
        cy: 3,
        r: 1,
      },
      {
        kind: 'circle',
        cx: 9,
        cy: 14,
        r: 1,
        fill: 'currentColor',
      },
      {
        kind: 'circle',
        cx: 15,
        cy: 14,
        r: 1,
        fill: 'currentColor',
      },
    ],
  },
  'box-list': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 3.5,
        y: 5,
        width: 11,
        height: 16,
        rx: 1.5,
      },
      {
        kind: 'rect',
        x: 7,
        y: 3,
        width: 4.5,
        height: 3,
        rx: 1,
      },
      {
        kind: 'path',
        d: 'M6.5 11h5M6.5 15h3',
      },
      {
        kind: 'rect',
        x: 15,
        y: 13,
        width: 6,
        height: 6,
        rx: 0.5,
      },
      {
        kind: 'path',
        d: 'M15 16h6M18 13v6',
      },
    ],
  },
  'box-up': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 4,
        y: 10,
        width: 16,
        height: 11,
        rx: 1,
      },
      {
        kind: 'path',
        d: 'M4 14h16',
      },
      {
        kind: 'path',
        d: 'M9 6l3-3 3 3',
      },
      {
        kind: 'path',
        d: 'M12 3v8',
      },
    ],
  },
  'building': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 4,
        y: 3,
        width: 16,
        height: 18,
        rx: 1,
      },
      {
        kind: 'path',
        d: 'M9 7h2',
      },
      {
        kind: 'path',
        d: 'M13 7h2',
      },
      {
        kind: 'path',
        d: 'M9 11h2',
      },
      {
        kind: 'path',
        d: 'M13 11h2',
      },
      {
        kind: 'path',
        d: 'M9 15h2',
      },
      {
        kind: 'path',
        d: 'M13 15h2',
      },
      {
        kind: 'path',
        d: 'M10 21v-3h4v3',
      },
    ],
  },
  'calculator': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 5,
        y: 3,
        width: 14,
        height: 18,
        rx: 2,
      },
      {
        kind: 'rect',
        x: 8,
        y: 6,
        width: 8,
        height: 3,
        rx: 0.5,
      },
      {
        kind: 'circle',
        cx: 9,
        cy: 13,
        r: 0.9,
        fill: 'currentColor',
      },
      {
        kind: 'circle',
        cx: 12,
        cy: 13,
        r: 0.9,
        fill: 'currentColor',
      },
      {
        kind: 'circle',
        cx: 15,
        cy: 13,
        r: 0.9,
        fill: 'currentColor',
      },
      {
        kind: 'circle',
        cx: 9,
        cy: 17,
        r: 0.9,
        fill: 'currentColor',
      },
      {
        kind: 'circle',
        cx: 12,
        cy: 17,
        r: 0.9,
        fill: 'currentColor',
      },
      {
        kind: 'circle',
        cx: 15,
        cy: 17,
        r: 0.9,
        fill: 'currentColor',
      },
    ],
  },
  'calendar-route': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 3,
        y: 5,
        width: 18,
        height: 16,
        rx: 1.5,
      },
      {
        kind: 'path',
        d: 'M3 10h18',
      },
      {
        kind: 'path',
        d: 'M8 3v4M16 3v4',
      },
      {
        kind: 'path',
        d: 'M6.5 15.5c1.5-2 3-2 4.5 0s3 2 4.5 0 1.5-2 3.5 0',
      },
    ],
  },
  'calendar': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 3,
        y: 5,
        width: 18,
        height: 16,
        rx: 2,
      },
      {
        kind: 'path',
        d: 'M3 10h18',
      },
      {
        kind: 'path',
        d: 'M8 3v4',
      },
      {
        kind: 'path',
        d: 'M16 3v4',
      },
    ],
  },
  'camera': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M4 8h3l2-3h6l2 3h3a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-8a2 2 0 0 1 2-2z',
      },
      {
        kind: 'circle',
        cx: 12,
        cy: 13,
        r: 3.5,
      },
    ],
  },
  'card': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 3,
        y: 6,
        width: 18,
        height: 13,
        rx: 2,
      },
      {
        kind: 'path',
        d: 'M3 10h18',
      },
      {
        kind: 'path',
        d: 'M7 15h3',
      },
    ],
  },
  'chat-star': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M4 5a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-6l-4 4v-4H6a2 2 0 0 1-2-2z',
      },
      {
        kind: 'path',
        d: 'M12 6.5l1.2 2.5 2.7.4-2 1.9.5 2.7L12 12.7l-2.4 1.3.5-2.7-2-1.9 2.7-.4z',
      },
    ],
  },
  'check': {
    strokeWidth: 2,
    elements: [
      {
        kind: 'path',
        d: 'M5 12.5l4.5 4.5L19 7',
      },
    ],
  },
  'chevron-down': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M6 9l6 6 6-6',
      },
    ],
  },
  'chevron-left': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M15 6l-6 6 6 6',
      },
    ],
  },
  'chevron-right': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M9 6l6 6-6 6',
      },
    ],
  },
  'chevron-up': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M6 15l6-6 6 6',
      },
    ],
  },
  'circle-minus': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'circle',
        cx: 12,
        cy: 12,
        r: 9,
      },
      {
        kind: 'path',
        d: 'M8 12h8',
      },
    ],
  },
  'circle-plus': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'circle',
        cx: 12,
        cy: 12,
        r: 9,
      },
      {
        kind: 'path',
        d: 'M12 8v8',
      },
      {
        kind: 'path',
        d: 'M8 12h8',
      },
    ],
  },
  'clipboard-search': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 4,
        y: 4,
        width: 13,
        height: 17,
        rx: 2,
      },
      {
        kind: 'rect',
        x: 8,
        y: 2.5,
        width: 5,
        height: 3,
        rx: 1,
      },
      {
        kind: 'path',
        d: 'M7.5 10h6',
      },
      {
        kind: 'circle',
        cx: 17,
        cy: 16,
        r: 3.2,
      },
      {
        kind: 'path',
        d: 'M19.4 18.4L21.5 20.5',
      },
    ],
  },
  'clipboard-user': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 3.5,
        y: 8,
        width: 10,
        height: 13,
        rx: 1,
      },
      {
        kind: 'path',
        d: 'M6 12h2M10 12h2M6 16h2M10 16h2',
      },
      {
        kind: 'path',
        d: 'M7.5 21v-2.5h2.5V21',
      },
      {
        kind: 'circle',
        cx: 18,
        cy: 8,
        r: 2.8,
      },
      {
        kind: 'path',
        d: 'M18 10.8V14',
      },
    ],
  },
  'clipboard': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 6,
        y: 4,
        width: 12,
        height: 17,
        rx: 2,
      },
      {
        kind: 'rect',
        x: 9,
        y: 2.5,
        width: 6,
        height: 3,
        rx: 1,
      },
      {
        kind: 'path',
        d: 'M9 11h6M9 15h4',
      },
    ],
  },
  'close': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M6 6l12 12M18 6L6 18',
      },
    ],
  },
  'coin': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'circle',
        cx: 12,
        cy: 12,
        r: 9,
      },
      {
        kind: 'path',
        d: 'M8 8l4 5 4-5',
      },
      {
        kind: 'path',
        d: 'M12 13v4',
      },
      {
        kind: 'path',
        d: 'M9 14h6',
      },
      {
        kind: 'path',
        d: 'M9 16h6',
      },
    ],
  },
  'copy': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 8,
        y: 8,
        width: 13,
        height: 13,
        rx: 2,
      },
      {
        kind: 'path',
        d: 'M4 16V5a2 2 0 0 1 2-2h11',
      },
    ],
  },
  'dashboard-megaphone': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'circle',
        cx: 12,
        cy: 12,
        r: 9.5,
      },
      {
        kind: 'circle',
        cx: 12,
        cy: 12,
        r: 5.8,
      },
      {
        kind: 'path',
        d: 'M8.8 11.4v1.2l3.4 1.3V10.1z',
        fill: 'currentColor',
      },
      {
        kind: 'path',
        d: 'M13.3 11.1a1.4 1.4 0 0 1 0 1.8',
      },
      {
        kind: 'path',
        d: 'M14.8 9.8a3 3 0 0 1 0 4.4',
      },
    ],
  },
  'dashboard-star': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'circle',
        cx: 12,
        cy: 12,
        r: 9.5,
      },
      {
        kind: 'circle',
        cx: 12,
        cy: 12,
        r: 5.8,
      },
      {
        kind: 'path',
        d: 'M12 8.5l1.2 2.42 2.68.39-1.94 1.89.46 2.67L12 14.61l-2.4 1.26.46-2.67L8.12 11.31l2.68-.39z',
        fill: 'currentColor',
      },
    ],
  },
  'download': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M12 4v12',
      },
      {
        kind: 'path',
        d: 'M5 13l7 7 7-7',
      },
      {
        kind: 'path',
        d: 'M4 20h16',
      },
    ],
  },
  'edit-pencil': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M14.5 4.5l5 5',
      },
      {
        kind: 'path',
        d: 'M3 21l5-1L20 8l-4-4L4 16z',
      },
    ],
  },
  'edit': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M16 3.5l4.5 4.5L8 20.5 3 21l.5-5z',
      },
    ],
  },
  'error': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'circle',
        cx: 12,
        cy: 12,
        r: 9,
      },
      {
        kind: 'path',
        d: 'M9 9l6 6',
      },
      {
        kind: 'path',
        d: 'M15 9l-6 6',
      },
    ],
  },
  'eye-off': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M3 3l18 18',
      },
      {
        kind: 'path',
        d: 'M10.6 10.6a3 3 0 0 0 4.2 4.2',
      },
      {
        kind: 'path',
        d: 'M9.4 5.3A10.5 10.5 0 0 1 12 5c6.5 0 10 7 10 7a17.6 17.6 0 0 1-3.6 4.5',
      },
      {
        kind: 'path',
        d: 'M6.6 6.6A17.7 17.7 0 0 0 2 12s3.5 7 10 7c1.7 0 3.2-.4 4.5-1',
      },
    ],
  },
  'eye': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M2 12s3.5-7 10-7 10 7 10 7-3.5 7-10 7-10-7-10-7z',
      },
      {
        kind: 'circle',
        cx: 12,
        cy: 12,
        r: 3,
      },
    ],
  },
  'file': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M14 3H6a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z',
      },
      {
        kind: 'path',
        d: 'M14 3v6h6',
      },
    ],
  },
  'filter': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M3 5h18l-7 9v6l-4-2v-4z',
      },
    ],
  },
  'flag': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M5 21V4',
      },
      {
        kind: 'path',
        d: 'M5 4h12l-2 4 2 4H5',
      },
    ],
  },
  'grid': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 4,
        y: 4,
        width: 7,
        height: 7,
        rx: 1,
      },
      {
        kind: 'rect',
        x: 13,
        y: 4,
        width: 7,
        height: 7,
        rx: 1,
      },
      {
        kind: 'rect',
        x: 4,
        y: 13,
        width: 7,
        height: 7,
        rx: 1,
      },
      {
        kind: 'rect',
        x: 13,
        y: 13,
        width: 7,
        height: 7,
        rx: 1,
      },
    ],
  },
  'heart': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M20.4 6.4a5 5 0 0 0-7.4-.4L12 7l-1-1a5 5 0 1 0-7 7l8 8 8-8a5 5 0 0 0 .4-6.6z',
      },
    ],
  },
  'home': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 3.25,
        y: 3.5,
        width: 17.5,
        height: 17,
        rx: 2.75,
      },
      {
        kind: 'path',
        d: 'M3.25 9.25h17.5',
      },
      {
        kind: 'path',
        d: 'M12 9.25v11.25',
      },
    ],
  },
  'image': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 3,
        y: 4,
        width: 18,
        height: 16,
        rx: 2,
      },
      {
        kind: 'circle',
        cx: 9,
        cy: 10,
        r: 2,
      },
      {
        kind: 'path',
        d: 'M21 15l-5-5L4 20',
      },
    ],
  },
  'info': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'circle',
        cx: 12,
        cy: 12,
        r: 9,
      },
      {
        kind: 'path',
        d: 'M12 11v5',
      },
      {
        kind: 'circle',
        cx: 12,
        cy: 8,
        r: 0.6,
        fill: 'currentColor',
      },
    ],
  },
  'keyboard': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 2.5,
        y: 6,
        width: 19,
        height: 12,
        rx: 2,
      },
      {
        kind: 'path',
        d: 'M6 10h.01M10 10h.01M14 10h.01M18 10h.01M7 14h10',
      },
    ],
  },
  'lightbulb': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M9 18h6',
      },
      {
        kind: 'path',
        d: 'M10 21h4',
      },
      {
        kind: 'path',
        d: 'M8 14a5 5 0 1 1 8 0c-1 1-1.5 2-1.5 3.5h-5C9.5 16 9 15 8 14z',
      },
    ],
  },
  'list': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M8 6h12',
      },
      {
        kind: 'path',
        d: 'M8 12h12',
      },
      {
        kind: 'path',
        d: 'M8 18h12',
      },
      {
        kind: 'circle',
        cx: 4,
        cy: 6,
        r: 1,
        fill: 'currentColor',
      },
      {
        kind: 'circle',
        cx: 4,
        cy: 12,
        r: 1,
        fill: 'currentColor',
      },
      {
        kind: 'circle',
        cx: 4,
        cy: 18,
        r: 1,
        fill: 'currentColor',
      },
    ],
  },
  'location': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M12 22s7-7.5 7-13a7 7 0 1 0-14 0c0 5.5 7 13 7 13z',
      },
      {
        kind: 'circle',
        cx: 12,
        cy: 9,
        r: 2.5,
      },
    ],
  },
  'lock': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 5,
        y: 11,
        width: 14,
        height: 9,
        rx: 2,
      },
      {
        kind: 'path',
        d: 'M8 11V8a4 4 0 0 1 8 0v3',
      },
    ],
  },
  'logout': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M14 5h5a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1h-5',
      },
      {
        kind: 'path',
        d: 'M3 12h12',
      },
      {
        kind: 'path',
        d: 'M15 12l-4-4',
      },
      {
        kind: 'path',
        d: 'M15 12l-4 4',
      },
    ],
  },
  'mail': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 3,
        y: 5,
        width: 18,
        height: 14,
        rx: 2,
      },
      {
        kind: 'path',
        d: 'M3 7l9 6 9-6',
      },
    ],
  },
  'menu': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M4 7h16M4 12h16M4 17h16',
      },
    ],
  },
  'mic-on': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 9,
        y: 3,
        width: 6,
        height: 12,
        rx: 3,
      },
      {
        kind: 'path',
        d: 'M5 11a7 7 0 0 0 14 0',
      },
      {
        kind: 'path',
        d: 'M12 18v3',
      },
    ],
  },
  'mic': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 9,
        y: 3,
        width: 6,
        height: 12,
        rx: 3,
      },
      {
        kind: 'path',
        d: 'M5 11a7 7 0 0 0 14 0',
      },
      {
        kind: 'path',
        d: 'M12 18v3',
      },
    ],
  },
  'more-h': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'circle',
        cx: 5,
        cy: 12,
        r: 1.5,
        fill: 'currentColor',
      },
      {
        kind: 'circle',
        cx: 12,
        cy: 12,
        r: 1.5,
        fill: 'currentColor',
      },
      {
        kind: 'circle',
        cx: 19,
        cy: 12,
        r: 1.5,
        fill: 'currentColor',
      },
    ],
  },
  'more-v': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'circle',
        cx: 12,
        cy: 5,
        r: 1.5,
        fill: 'currentColor',
      },
      {
        kind: 'circle',
        cx: 12,
        cy: 12,
        r: 1.5,
        fill: 'currentColor',
      },
      {
        kind: 'circle',
        cx: 12,
        cy: 19,
        r: 1.5,
        fill: 'currentColor',
      },
    ],
  },
  'order': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 5,
        y: 3,
        width: 14,
        height: 18,
        rx: 2,
      },
      {
        kind: 'path',
        d: 'M9 8h6',
      },
      {
        kind: 'path',
        d: 'M9 12h6',
      },
      {
        kind: 'path',
        d: 'M9 16h4',
      },
    ],
  },
  'package': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M21 8l-9-5-9 5v8l9 5 9-5z',
      },
      {
        kind: 'path',
        d: 'M3 8l9 5 9-5',
      },
      {
        kind: 'path',
        d: 'M12 13v8',
      },
      {
        kind: 'path',
        d: 'M7.5 5.5l9 5',
      },
    ],
  },
  'paperclip': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M21 11l-9 9a5 5 0 0 1-7-7l9-9a3.5 3.5 0 0 1 5 5l-9 9a2 2 0 0 1-3-3l8-8',
      },
    ],
  },
  'pause': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 6,
        y: 5,
        width: 4,
        height: 14,
        rx: 1,
      },
      {
        kind: 'rect',
        x: 14,
        y: 5,
        width: 4,
        height: 14,
        rx: 1,
      },
    ],
  },
  'phone': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M5 4h3l2 5-2.5 1.5a11 11 0 0 0 6 6L15 14l5 2v3a2 2 0 0 1-2 2A16 16 0 0 1 3 6a2 2 0 0 1 2-2z',
      },
    ],
  },
  'pin-search': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M12 21s7-7 7-12a7 7 0 1 0-14 0c0 5 7 12 7 12z',
      },
      {
        kind: 'circle',
        cx: 12,
        cy: 8.5,
        r: 2.2,
      },
      {
        kind: 'path',
        d: 'M13.6 10.1l1.8 1.8',
      },
    ],
  },
  'play': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M6 4l14 8-14 8z',
      },
    ],
  },
  'plus': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M12 5v14M5 12h14',
      },
    ],
  },
  'qr': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 4,
        y: 4,
        width: 6,
        height: 6,
      },
      {
        kind: 'rect',
        x: 14,
        y: 4,
        width: 6,
        height: 6,
      },
      {
        kind: 'rect',
        x: 4,
        y: 14,
        width: 6,
        height: 6,
      },
      {
        kind: 'path',
        d: 'M14 14h2v2h-2zM18 14h2v2h-2zM14 18h2v2h-2zM18 18h2v2h-2z',
        fill: 'currentColor',
      },
    ],
  },
  'refresh': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M3 12a9 9 0 0 1 15.5-6.3L21 8',
      },
      {
        kind: 'path',
        d: 'M21 3v5h-5',
      },
      {
        kind: 'path',
        d: 'M21 12a9 9 0 0 1-15.5 6.3L3 16',
      },
      {
        kind: 'path',
        d: 'M3 21v-5h5',
      },
    ],
  },
  'retry': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M21 12a9 9 0 1 1-3.5-7.1',
      },
      {
        kind: 'path',
        d: 'M21 4v5h-5',
      },
    ],
  },
  'route': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'circle',
        cx: 6,
        cy: 19,
        r: 3,
      },
      {
        kind: 'circle',
        cx: 18,
        cy: 5,
        r: 3,
      },
      {
        kind: 'path',
        d: 'M6 16V9a4 4 0 0 1 4-4h4',
      },
      {
        kind: 'path',
        d: 'M18 8v7a4 4 0 0 1-4 4h-4',
      },
    ],
  },
  'scan': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M4 8V5a1 1 0 0 1 1-1h3',
      },
      {
        kind: 'path',
        d: 'M16 4h3a1 1 0 0 1 1 1v3',
      },
      {
        kind: 'path',
        d: 'M20 16v3a1 1 0 0 1-1 1h-3',
      },
      {
        kind: 'path',
        d: 'M8 20H5a1 1 0 0 1-1-1v-3',
      },
      {
        kind: 'path',
        d: 'M4 12h16',
      },
    ],
  },
  'scanner': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 13,
        y: 5,
        width: 8,
        height: 14,
        rx: 1.5,
      },
      {
        kind: 'path',
        d: 'M13 16h8',
      },
      {
        kind: 'circle',
        cx: 17,
        cy: 17.6,
        r: 0.9,
        fill: 'currentColor',
      },
      {
        kind: 'path',
        d: 'M3 8v8M5.5 8v8M8 8v8M10.5 8v8',
      },
      {
        kind: 'path',
        d: 'M11 12h2',
      },
    ],
  },
  'search': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'circle',
        cx: 11,
        cy: 11,
        r: 7,
      },
      {
        kind: 'path',
        d: 'M20 20l-3.5-3.5',
      },
    ],
  },
  'send': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M12 19V5',
      },
      {
        kind: 'path',
        d: 'M5 12l7-7 7 7',
      },
    ],
  },
  'settings': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'circle',
        cx: 12,
        cy: 12,
        r: 3,
      },
      {
        kind: 'path',
        d: 'M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z',
      },
    ],
  },
  'share': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'circle',
        cx: 6,
        cy: 12,
        r: 3,
      },
      {
        kind: 'circle',
        cx: 18,
        cy: 6,
        r: 3,
      },
      {
        kind: 'circle',
        cx: 18,
        cy: 18,
        r: 3,
      },
      {
        kind: 'path',
        d: 'M8.5 10.5l7-3',
      },
      {
        kind: 'path',
        d: 'M8.5 13.5l7 3',
      },
    ],
  },
  'shelf-pay': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M3 9h18M3 15h18M3 21h18',
      },
      {
        kind: 'rect',
        x: 5,
        y: 5,
        width: 3.5,
        height: 4,
      },
      {
        kind: 'rect',
        x: 11,
        y: 11,
        width: 3.5,
        height: 4,
      },
      {
        kind: 'rect',
        x: 15,
        y: 3,
        width: 4,
        height: 3,
        rx: 0.5,
      },
      {
        kind: 'path',
        d: 'M16 4.5h2',
      },
    ],
  },
  'shield-check': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M12 3l8 3v6c0 5-3.5 8-8 9-4.5-1-8-4-8-9V6z',
      },
      {
        kind: 'path',
        d: 'M9 12l2 2 4-4',
      },
    ],
  },
  'sort': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M7 4v16',
      },
      {
        kind: 'path',
        d: 'M3 8l4-4 4 4',
      },
      {
        kind: 'path',
        d: 'M17 4v16',
      },
      {
        kind: 'path',
        d: 'M13 16l4 4 4-4',
      },
    ],
  },
  'sound': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M11 5L6 9H3v6h3l5 4V5z',
      },
      {
        kind: 'path',
        d: 'M15.5 8.5a5 5 0 0 1 0 7',
      },
      {
        kind: 'path',
        d: 'M18 6a8 8 0 0 1 0 12',
      },
    ],
  },
  'spark': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M5 3v4',
      },
      {
        kind: 'path',
        d: 'M3 5h4',
      },
      {
        kind: 'path',
        d: 'M19 14v4',
      },
      {
        kind: 'path',
        d: 'M17 16h4',
      },
      {
        kind: 'path',
        d: 'M12 4l2 5 5 2-5 2-2 5-2-5-5-2 5-2z',
      },
    ],
  },
  'star': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M12 3l2.7 5.7 6.3.9-4.5 4.4 1 6.3L12 17.5 6.5 20.3l1-6.3L3 9.6l6.3-.9z',
      },
    ],
  },
  'stop': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'rect',
        x: 6,
        y: 6,
        width: 12,
        height: 12,
        rx: 1.5,
      },
    ],
  },
  'storefront-ai': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M4 10l2-4h12l2 4z',
      },
      {
        kind: 'path',
        d: 'M4 10h16',
      },
      {
        kind: 'path',
        d: 'M5 10v11h14V10',
      },
      {
        kind: 'circle',
        cx: 11,
        cy: 15.5,
        r: 2.5,
      },
      {
        kind: 'path',
        d: 'M12.8 17.3l2.4 2.4',
      },
      {
        kind: 'path',
        d: 'M19.2 2.5l.55 1.55 1.55.55-1.55.55-.55 1.55-.55-1.55-1.55-.55 1.55-.55z',
        fill: 'currentColor',
      },
    ],
  },
  'storefront-arrow': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M9 11l2-4h8l2 4z',
      },
      {
        kind: 'path',
        d: 'M9 11h12',
      },
      {
        kind: 'path',
        d: 'M10 11v10h10V11',
      },
      {
        kind: 'path',
        d: 'M13 21v-5a2 2 0 0 1 4 0v5',
      },
      {
        kind: 'path',
        d: 'M2.5 16h5',
      },
      {
        kind: 'path',
        d: 'M5 13.5L7.5 16 5 18.5',
      },
    ],
  },
  'storefront-check': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M4 10l2-4h12l2 4z',
      },
      {
        kind: 'path',
        d: 'M4 10h16',
      },
      {
        kind: 'path',
        d: 'M5 10v11h14V10',
      },
      {
        kind: 'circle',
        cx: 12,
        cy: 16.5,
        r: 3.6,
      },
      {
        kind: 'path',
        d: 'M10.2 16.5l1.4 1.4L14 15.4',
      },
    ],
  },
  'storefront-tag': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M4 10l2-4h12l2 4z',
      },
      {
        kind: 'path',
        d: 'M4 10h16',
      },
      {
        kind: 'path',
        d: 'M5 10v11h14V10',
      },
      {
        kind: 'path',
        d: 'M7.5 14h5.3l2.5 2.5L12.8 19H7.5z',
      },
      {
        kind: 'circle',
        cx: 9.3,
        cy: 16.5,
        r: 0.75,
        fill: 'currentColor',
      },
    ],
  },
  'storefront': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M4 10l2-4h12l2 4z',
      },
      {
        kind: 'path',
        d: 'M4 10h16',
      },
      {
        kind: 'path',
        d: 'M5 10v11h14V10',
      },
      {
        kind: 'path',
        d: 'M10 21v-5a2 2 0 0 1 4 0v5',
      },
      {
        kind: 'rect',
        x: 6.5,
        y: 12,
        width: 2.5,
        height: 2.5,
        rx: 0.3,
      },
      {
        kind: 'rect',
        x: 15,
        y: 12,
        width: 2.5,
        height: 2.5,
        rx: 0.3,
      },
    ],
  },
  'success': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'circle',
        cx: 12,
        cy: 12,
        r: 9,
      },
      {
        kind: 'path',
        d: 'M8 12.5l3 3 5-6',
      },
    ],
  },
  'tag': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M3 12V4a1 1 0 0 1 1-1h8l9 9-9 9z',
      },
      {
        kind: 'circle',
        cx: 8,
        cy: 8,
        r: 1.4,
        fill: 'currentColor',
      },
    ],
  },
  'thinking': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M20 11.5a8 8 0 1 0-14.5 4.7L4 21l5-1.4a8 8 0 0 0 11-8.1z',
      },
      {
        kind: 'path',
        d: 'M9 11h.01M12 11h.01M15 11h.01',
      },
    ],
  },
  'trash': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M4 7h16',
      },
      {
        kind: 'path',
        d: 'M9 7V4h6v3',
      },
      {
        kind: 'path',
        d: 'M6 7l1 13a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2l1-13',
      },
    ],
  },
  'upload': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M12 16V4',
      },
      {
        kind: 'path',
        d: 'M5 11l7-7 7 7',
      },
      {
        kind: 'path',
        d: 'M4 20h16',
      },
    ],
  },
  'user': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'circle',
        cx: 12,
        cy: 12,
        r: 9,
      },
      {
        kind: 'circle',
        cx: 12,
        cy: 10.25,
        r: 2.6,
      },
      {
        kind: 'path',
        d: 'M6.7 18.6c1-2.55 3-3.85 5.3-3.85s4.3 1.3 5.3 3.85',
      },
    ],
  },
  'users-search': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'circle',
        cx: 8,
        cy: 9,
        r: 3,
      },
      {
        kind: 'path',
        d: 'M2.5 20a5.5 5.5 0 0 1 11 0',
      },
      {
        kind: 'circle',
        cx: 15.5,
        cy: 11,
        r: 2.3,
      },
      {
        kind: 'path',
        d: 'M12 20a3.5 3.5 0 0 1 7 0',
      },
      {
        kind: 'circle',
        cx: 18.5,
        cy: 5,
        r: 2.2,
      },
      {
        kind: 'path',
        d: 'M20.1 6.6l1.9 1.9',
      },
    ],
  },
  'visit': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M3 21V9l3-5h12l3 5v12',
      },
      {
        kind: 'path',
        d: 'M3 9h18',
      },
      {
        kind: 'path',
        d: 'M10 21v-5h4v5',
      },
      {
        kind: 'path',
        d: 'M7 13h2',
      },
    ],
  },
  'warning': {
    strokeWidth: 1.75,
    elements: [
      {
        kind: 'path',
        d: 'M12 3l10 17H2z',
      },
      {
        kind: 'path',
        d: 'M12 10v5',
      },
      {
        kind: 'circle',
        cx: 12,
        cy: 18,
        r: 0.6,
        fill: 'currentColor',
      },
    ],
  },
};

export const ICON_NAMES: IconName[] = [
  'alert',
  'app-fallback',
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'arrow-up',
  'attachment',
  'bag-check',
  'bell',
  'bot',
  'box-list',
  'box-up',
  'building',
  'calculator',
  'calendar-route',
  'calendar',
  'camera',
  'card',
  'chat-star',
  'check',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'circle-minus',
  'circle-plus',
  'clipboard-search',
  'clipboard-user',
  'clipboard',
  'close',
  'coin',
  'copy',
  'dashboard-megaphone',
  'dashboard-star',
  'download',
  'edit-pencil',
  'edit',
  'error',
  'eye-off',
  'eye',
  'file',
  'filter',
  'flag',
  'grid',
  'heart',
  'home',
  'image',
  'info',
  'keyboard',
  'lightbulb',
  'list',
  'location',
  'lock',
  'logout',
  'mail',
  'menu',
  'mic-on',
  'mic',
  'more-h',
  'more-v',
  'order',
  'package',
  'paperclip',
  'pause',
  'phone',
  'pin-search',
  'play',
  'plus',
  'qr',
  'refresh',
  'retry',
  'route',
  'scan',
  'scanner',
  'search',
  'send',
  'settings',
  'share',
  'shelf-pay',
  'shield-check',
  'sort',
  'sound',
  'spark',
  'star',
  'stop',
  'storefront-ai',
  'storefront-arrow',
  'storefront-check',
  'storefront-tag',
  'storefront',
  'success',
  'tag',
  'thinking',
  'trash',
  'upload',
  'user',
  'users-search',
  'visit',
  'warning',
];
