export const sceneIds = [
  'foundation',
  'actions',
  'feedback',
  'forms',
  'navigation',
  'collections',
  'media',
  'business',
] as const;

export type SceneId = (typeof sceneIds)[number];

export const publicComponentIds = [
  'Avatar',
  'AvatarGroup',
  'BlurLayer',
  'BorderBeam',
  'Button',
  'Card',
  'Carousel',
  'Cell',
  'List',
  'Checkbox',
  'Chip',
  'CircularProgress',
  'ConfirmHost',
  'DrawerHeader',
  'Empty',
  'EntryCard',
  'Form',
  'FormGroup',
  'FormRow',
  'Grid',
  'Icon',
  'IconButton',
  'Input',
  'Logo',
  'NavBar',
  'PasswordInput',
  'Pulse',
  'PulseDot',
  'Radio',
  'Reveal',
  'Ribbon',
  'Search',
  'Segmented',
  'Skeleton',
  'Spinner',
  'StatusDot',
  'Stepper',
  'Switch',
  'TabBar',
  'Tabs',
  'Tag',
  'Textarea',
  'Thumbnail',
  'ToastHost',
  'GradientWash',
  'RadialHalo',
  'ScreenBackdrop',
  'GlassStats',
  'AvatarWithRing',
  'VersionPill',
] as const;

export type PublicComponentId = (typeof publicComponentIds)[number];

export type ComponentCatalogEntry = Readonly<{
  id: PublicComponentId;
  scene: SceneId;
  states: readonly [string, ...string[]];
}>;

export const componentCatalog = [
  {
    id: 'Icon',
    scene: 'foundation',
    states: ['图标全集', '名称检索', '尺寸', '颜色', '无障碍隐藏'],
  },
  {
    id: 'Button',
    scene: 'actions',
    states: ['变体', '尺寸', '通栏', '前后图标', '禁用', '加载'],
  },
  {
    id: 'IconButton',
    scene: 'actions',
    states: ['变体', '尺寸', '无障碍名称', '禁用', '加载'],
  },
  {
    id: 'Chip',
    scene: 'actions',
    states: ['静态', '可点击', '未选中', '选中', '图标', '禁用', '处理中'],
  },
  { id: 'Tag', scene: 'actions', states: ['变体', '尺寸'] },
  {
    id: 'StatusDot',
    scene: 'actions',
    states: ['pending/active/done/error', 'flat/soft', '尺寸', '无障碍名称'],
  },
  {
    id: 'Empty',
    scene: 'feedback',
    states: ['标题', '描述', '自定义图标', '调用方空数据边界'],
  },
  { id: 'Skeleton', scene: 'feedback', states: ['line', 'rect', 'circle'] },
  {
    id: 'CircularProgress',
    scene: 'feedback',
    states: ['确定进度', '中央百分比', '无障碍值'],
  },
  { id: 'Spinner', scene: 'feedback', states: ['尺寸', '颜色', '描边宽度'] },
  {
    id: 'BorderBeam',
    scene: 'feedback',
    states: [
      '默认',
      '停用',
      '颜色',
      '时长',
      '线宽',
      '流光长度',
      '圆角',
      '减少动态效果',
    ],
  },
  {
    id: 'Pulse',
    scene: 'feedback',
    states: ['默认', '透明度区间', '时长', '延迟', '减少动态效果'],
  },
  {
    id: 'PulseDot',
    scene: 'feedback',
    states: ['默认', '尺寸', '颜色', '自定义节奏', '减少动态效果'],
  },
  {
    id: 'Reveal',
    scene: 'feedback',
    states: ['入场', '时长', '容器样式', '减少动态效果'],
  },
  {
    id: 'BlurLayer',
    scene: 'feedback',
    states: ['soft', 'strong', '自定义 tint', '亮暗主题'],
  },
  {
    id: 'ConfirmHost',
    scene: 'feedback',
    states: ['确认', '取消', '危险操作', '重入'],
  },
  {
    id: 'ToastHost',
    scene: 'feedback',
    states: ['类型', '位置', '持续时间', 'latest wins'],
  },
  {
    id: 'Input',
    scene: 'forms',
    states: [
      '受控',
      '非受控',
      '空闲',
      '聚焦',
      '已填写',
      '错误',
      '禁用',
      '可编辑',
      '只读',
      '前后展示槽',
      '操作槽',
    ],
  },
  {
    id: 'PasswordInput',
    scene: 'forms',
    states: ['受控', '隐藏', '显示', '错误', '禁用', '安全结果'],
  },
  {
    id: 'Textarea',
    scene: 'forms',
    states: ['受控', '非受控', '错误', '禁用', '字数限制'],
  },
  {
    id: 'Search',
    scene: 'forms',
    states: ['受控', '非受控', '清除', '禁用', '提交'],
  },
  {
    id: 'Checkbox',
    scene: 'forms',
    states: ['未选中', '选中', '禁用', '无障碍状态'],
  },
  {
    id: 'Radio',
    scene: 'forms',
    states: ['未选中', '选中', '分组', '禁用'],
  },
  { id: 'Switch', scene: 'forms', states: ['关闭', '开启', '禁用'] },
  {
    id: 'Stepper',
    scene: 'forms',
    states: [
      '最小值',
      '中间值',
      '最大值',
      '步长',
      '零范围',
      '禁用',
      '尺寸',
      '格式化值',
    ],
  },
  { id: 'Form', scene: 'forms', states: ['单分组', '多分组'] },
  { id: 'FormGroup', scene: 'forms', states: ['有标题', '无标题'] },
  {
    id: 'FormRow',
    scene: 'forms',
    states: ['默认', '必填', '错误', '无障碍控件'],
  },
  {
    id: 'NavBar',
    scene: 'navigation',
    states: [
      '标题',
      '返回',
      '左右操作',
      '安全区',
      'default',
      'brand',
      'transparent',
    ],
  },
  {
    id: 'DrawerHeader',
    scene: 'navigation',
    states: ['用户名', '副标题', '头像 source', '首字回退'],
  },
  {
    id: 'Tabs',
    scene: 'navigation',
    states: ['选中项', '切换', '禁用项', '整体禁用'],
  },
  {
    id: 'Segmented',
    scene: 'navigation',
    states: ['选中项', '尺寸', '禁用'],
  },
  {
    id: 'TabBar',
    scene: 'navigation',
    states: ['选中项', '数字徽标', '99+ 徽标', '无障碍语义'],
  },
  {
    id: 'Card',
    scene: 'collections',
    states: ['default', 'plain', 'bare', 'fill'],
  },
  {
    id: 'Ribbon',
    scene: 'collections',
    states: ['brand', 'danger', '右上定位', '可选读屏文案'],
  },
  {
    id: 'Cell',
    scene: 'collections',
    states: ['static', 'action', 'control', 'arrow', 'danger', 'disabled'],
  },
  {
    id: 'List',
    scene: 'collections',
    states: ['grouped', 'flush', 'full divider', 'no divider'],
  },
  {
    id: 'Grid',
    scene: 'collections',
    states: ['static', 'clickable', '列数', 'card', 'badge'],
  },
  {
    id: 'EntryCard',
    scene: 'collections',
    states: ['static', 'clickable', '有副标题', '无副标题'],
  },
  {
    id: 'Carousel',
    scene: 'collections',
    states: [
      '单页',
      '多页',
      '可操作项',
      '指示器',
      '自动播放',
      '循环',
      'ref 控制',
    ],
  },
  {
    id: 'Avatar',
    scene: 'media',
    states: [
      'brand/info/soft/neutral',
      'xs/sm/md/lg/xl',
      'circle/square',
      '图片',
      '回退文字',
    ],
  },
  {
    id: 'AvatarGroup',
    scene: 'media',
    states: ['circle/square', '未溢出/溢出', '静态/可点击'],
  },
  {
    id: 'Thumbnail',
    scene: 'media',
    states: ['sm/md/lg', 'uri/source', '选中', '无障碍名称', '加载失败'],
  },
  {
    id: 'Logo',
    scene: 'media',
    states: ['source', '尺寸', '圆角', '装饰/有意义图片'],
  },
  {
    id: 'GradientWash',
    scene: 'business',
    states: ['单色透明度', '自定义 stops', '高度', 'gradient id'],
  },
  {
    id: 'RadialHalo',
    scene: 'business',
    states: ['圆形', '椭圆', 'maxOpacity', '自定义 stops', 'gradient id'],
  },
  {
    id: 'ScreenBackdrop',
    scene: 'business',
    states: ['预设', '自定义 halo', '亮暗主题'],
  },
  {
    id: 'GlassStats',
    scene: 'business',
    states: ['2 列', '3 列', '4 列', '已格式化值'],
  },
  {
    id: 'AvatarWithRing',
    scene: 'business',
    states: ['字符', '尺寸', 'ring 颜色'],
  },
  {
    id: 'VersionPill',
    scene: 'business',
    states: ['状态', '版本文案'],
  },
] as const satisfies readonly ComponentCatalogEntry[];

export const requiredRuntimeApis = [
  'ThemeProvider',
  'useTheme',
  'useColors',
  'useShadow',
  'useFontScale',
  'useThemedStyles',
  'usePrefersReducedMotion',
  'normalizeFontScale',
  'scaleFontMetric',
  'r',
  'rf',
  'lightColors',
  'darkColors',
  'avatarGradient',
  'BRAND_ORANGE',
  'warmOrangePalette',
  'lightShadow',
  'darkShadow',
  'fontMono',
  'type',
  'fw',
  'space',
  'radius',
  'avatar',
  'icon',
  'control',
  'dim',
  'fixed',
  'motion',
  'pressedOpacity',
  'blur',
  'ICONS',
  'ICON_NAMES',
  'childTestID',
  'createLogger',
  'setLogLevel',
  'getLogLevel',
  'addTransport',
  'removeTransport',
  'consoleTransport',
  'confirm',
  'toast',
  'usePulse',
  'useSvgId',
] as const;
