#!/usr/bin/env node
/**
 * 把 src/icons/svg/*.svg 编译成 src/icons/data.ts。
 * 用法:`node scripts/build-icons.js`。无第三方依赖,纯 regex 抽属性。
 *
 * 支持元素:<path d=.../>、<rect x y width height rx?/>、<circle cx cy r/>。
 * 其它(polyline / polygon)请先转 path。
 */
const fs = require('fs');
const path = require('path');

const SVG_DIR = path.resolve(__dirname, '../src/icons/svg');
const OUT = path.resolve(__dirname, '../src/icons/data.ts');
const DEFAULT_STROKE = 1.75;

const attr = (tag, name) => {
  const m = tag.match(new RegExp(`${name}\\s*=\\s*"([^"]*)"`));
  return m ? m[1] : undefined;
};
const num = (v) => (v === undefined ? undefined : Number(v));
const elFill = (tag) =>
  attr(tag, 'fill') === 'currentColor' ? 'currentColor' : undefined;

function parseSvg(src) {
  const stroke =
    num(attr(src.match(/<svg[^>]*>/)?.[0] ?? '', 'stroke-width')) ??
    DEFAULT_STROKE;
  const elements = [];
  for (const m of src.matchAll(/<(path|rect|circle)\b([^/>]*)\/?>/g)) {
    const [, kind, raw] = m;
    const tag = `<${kind}${raw}>`;
    const fill = elFill(tag);
    if (kind === 'path') {
      const d = attr(tag, 'd');
      if (d) elements.push({ kind, d, ...(fill && { fill }) });
    } else if (kind === 'rect') {
      const e = {
        kind,
        x: num(attr(tag, 'x')) ?? 0,
        y: num(attr(tag, 'y')) ?? 0,
        width: num(attr(tag, 'width')) ?? 0,
        height: num(attr(tag, 'height')) ?? 0,
      };
      const rx = num(attr(tag, 'rx'));
      if (rx !== undefined) e.rx = rx;
      if (fill) e.fill = fill;
      elements.push(e);
    } else if (kind === 'circle') {
      const e = {
        kind,
        cx: num(attr(tag, 'cx')) ?? 0,
        cy: num(attr(tag, 'cy')) ?? 0,
        r: num(attr(tag, 'r')) ?? 0,
      };
      if (fill) e.fill = fill;
      elements.push(e);
    }
  }
  return { strokeWidth: stroke, elements };
}

const files = fs
  .readdirSync(SVG_DIR)
  .filter((f) => f.endsWith('.svg'))
  .sort();
const names = files.map((f) => f.replace(/\.svg$/, ''));
const icons = Object.fromEntries(
  files.map((f) => [
    f.replace(/\.svg$/, ''),
    parseSvg(fs.readFileSync(path.join(SVG_DIR, f), 'utf8')),
  ])
);

const union = names.map((n) => `'${n}'`).join(' | ');
const body = names
  .map(
    (n) =>
      `  '${n}': ${JSON.stringify(icons[n], null, 4).replace(/\n/g, '\n  ')},`
  )
  .join('\n');
const list = names.map((n) => `  '${n}',`).join('\n');

fs.writeFileSync(
  OUT,
  `// AUTO-GENERATED by scripts/build-icons.js — DO NOT EDIT BY HAND.
// Source: src/icons/svg/*.svg
// To regenerate: \`node scripts/build-icons.js\`

import type { IconDef } from './types';

export type IconName = ${union};

export const ICONS: Record<IconName, IconDef> = {
${body}
};

export const ICON_NAMES: IconName[] = [
${list}
];
`
);
console.log(
  `build-icons: wrote ${names.length} icons → ${path.relative(process.cwd(), OUT)}`
);
