import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'UNIF-DESIGN',
    {
      type: 'category',
      label: '设计原则',
      items: [
        'design/intro',
        'design/principles',
        'design/voice',
        'design/donts',
      ],
    },
    {
      type: 'category',
      label: 'Design Tokens',
      items: [
        'design/tokens/colors',
        'design/tokens/typography',
        'design/tokens/spacing-radii-shadows',
        'design/tokens/motion',
      ],
    },
    {
      type: 'category',
      label: '组件',
      items: [
        'components/overview',
        'components/avatar',
        'components/avatar-with-ring',
        'components/blur-layer',
        'components/button',
        'components/card',
        'components/carousel',
        'components/cell',
        'components/checkbox',
        'components/chip',
        'components/confirm',
        'components/decorations',
        'components/empty',
        'components/entry-card',
        'components/form',
        'components/glass-stats',
        'components/grid',
        'components/icon-button',
        'components/icons',
        'components/input',
        'components/loading',
        'components/logo',
        'components/navbar',
        'components/password-input',
        'components/pulse',
        'components/radio',
        'components/search',
        'components/skeleton',
        'components/status-dot',
        'components/stepper',
        'components/switch',
        'components/tabbar',
        'components/tabs',
        'components/tag',
        'components/text-field',
        'components/textarea',
        'components/thumbnail',
        'components/toast',
        'components/version-pill',
      ],
    },
  ],
};

export default sidebars;
